Extended Object Normalization
rollbar/rollbar-php pull request #497
Opened 2020-08-19 02:07 UTC by ragboyjr

- Added better support for serializing common
  types of classes since a lot of classes use
  private fields which make the default object
  normalization basically useless

Signed-off-by: RJ Garcia <ragboyjr@icloud.com>

## Description of the change

> Description here
## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues
## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

2020-12-02 17:46 UTC, bishopb requested changes
Thanks for these improvements! They seem like a good value add. There are a few changes necessary, but otherwise we should be good to go.

2020-12-02 17:46 UTC, bishopb commented on src/Utilities.php
> +                $serialized['value'] = $obj->toString();
The method `toString` we would _think_ would return a `string`, however that's not guaranteed: someone could do `function toString(): resource { return fopen($this->path, 'r'); }`. Recommend that the output of `$obj->toString()` pass through `serializeForRollbar` to ensure it's serialized. That may require some juggling of the checks.

2020-12-02 17:46 UTC, bishopb commented on src/Utilities.php
> +            } elseif (method_exists($obj, 'toArray')) {
Same applies here as it did with the `toString` comment: there's no guarantee that `toArray` actually returns an `array`.

2020-12-02 17:46 UTC, bishopb commented on src/Utilities.php
> +        } catch (\Throwable $e) {
`Throwable` is not safe for 5.x, which this version of the Rollbar library supports. We also need a `Exception` block to handle that version.

2020-12-02 17:46 UTC, bishopb commented on tests/TestHelpers/ObjectSerialization/JsonSerializable.php
> +namespace Rollbar\TestHelpers\ObjectSerialization;
Nit: these may not pass linting, as we have `namespace` beside the `<?php` in other files. However, we will be changing this in the next major iteration of this library in order to support `strict_types`.

2022-12-20 20:35 UTC, danielmorell commented
I am closing this PR as it has become stale.

2022-12-20 20:35 UTC, closed without merging